### ISSUE TITLE
Explicitly specify MJML bg AND font colors

### ISSUE THREAD

**Issue by ConcernedHobbit** [TKOaly/baseball-bat#1]
Currently the mail template shows wrong on iOS mail as text color is not explicitly specified but assumed to be black (it is white when in iOS night mode)

![image](https://user-images.githubusercontent.com/1447279/209661937-b624fa59-15db-422d-9f86-05295608605d.jpeg)

**Comment by meklu** [comment]
According to the [mjml documentation](https://documentation.mjml.io/#mj-text), the default text color for `<mj-text>` elements is explicitly set to `#000000`. The live editor on there seems to confirm this: `<mj-text>foo</mj-text>` turns into the following HTML: `<div style="/* editorial snip */ color:#000000;">foo</div>`

It would be cool if you could provide an anonymized version of the actual generated HTML source of the message. It may be that Apple does something very destructive when it encounters explicitly black text which should make this their problem. If that proves to be the case, this could possibly still be worked around by setting the text color to something stupid, like `#020202` for instance.

**Comment by ConcernedHobbit** [comment]
seems to be fixed in iOS 16.4

**Comment by ConcernedHobbit** [comment]
cannot recreate
